name: Test
on:

  push:
    branches: [ "*" ]

jobs:

ci:
    runs-on: ubuntu-latest

    steps:
 
      - uses: actions/checkout@v3
      - uses: actions/seetup-node@v2
        node-version: 10
      - run: npm ci
      - run: npm run jest 
      - run: npm run build

